CCDNMessage\MessageBundle\Entity\Thread:
    type: entity
    table: cc_message_thread
    repositoryClass: CCDNMessage\MessageBundle\Repository\ThreadRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        messages:
            targetEntity: CCDNMessage\MessageBundle\Entity\Message
            mappedBy: thread
